<?php

namespace ContainerMkEPiLu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRol2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.EggCzqy.App\Entity\Rol' shared service.
     *
     * @return \App\Entity\Rol
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.EggCzqy": it needs an instance of "App\\Entity\\Rol" but this type has been excluded in "config/services.yaml".');
    }
}
