nelmio_cors:
    paths:
        '^/':
            allow_origin: ['*']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            allow_headers: ['Content-Type', 'Authorization']
            max_age: 3600
