<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class TipoMesa extends \App\Entity\TipoMesa implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'ancho' => [parent::class, 'ancho', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'juegos' => [parent::class, 'juegos', null],
        "\0".parent::class."\0".'largo' => [parent::class, 'largo', null],
        "\0".parent::class."\0".'mesas' => [parent::class, 'mesas', null],
        'ancho' => [parent::class, 'ancho', null],
        'id' => [parent::class, 'id', null],
        'juegos' => [parent::class, 'juegos', null],
        'largo' => [parent::class, 'largo', null],
        'mesas' => [parent::class, 'mesas', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
