<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Juego extends \App\Entity\Juego implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'imagen' => [parent::class, 'imagen', null],
        "\0".parent::class."\0".'max_jug' => [parent::class, 'max_jug', null],
        "\0".parent::class."\0".'min_jug' => [parent::class, 'min_jug', null],
        "\0".parent::class."\0".'nombre' => [parent::class, 'nombre', null],
        "\0".parent::class."\0".'reservas' => [parent::class, 'reservas', null],
        "\0".parent::class."\0".'tipomesa' => [parent::class, 'tipomesa', null],
        'id' => [parent::class, 'id', null],
        'imagen' => [parent::class, 'imagen', null],
        'max_jug' => [parent::class, 'max_jug', null],
        'min_jug' => [parent::class, 'min_jug', null],
        'nombre' => [parent::class, 'nombre', null],
        'reservas' => [parent::class, 'reservas', null],
        'tipomesa' => [parent::class, 'tipomesa', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
