<?php

namespace ContainerLXwdzuf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTipoMesaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator._u1C5vC.App\Entity\TipoMesa' shared service.
     *
     * @return \App\Entity\TipoMesa
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator._u1C5vC": it needs an instance of "App\\Entity\\TipoMesa" but this type has been excluded in "config/services.yaml".');
    }
}
