<?php

namespace Container2cs75b5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_I8vUD2PService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.i8vUD2P' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.i8vUD2P'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'mesa' => ['privates', '.errored..service_locator.i8vUD2P.App\\Entity\\Mesa', NULL, 'Cannot autowire service ".service_locator.i8vUD2P": it needs an instance of "App\\Entity\\Mesa" but this type has been excluded in "config/services.yaml".'],
        ], [
            'mesa' => 'App\\Entity\\Mesa',
        ]);
    }
}
