<?php

namespace ContainerCV58Hm0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMesaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.a0WsX_G.App\Entity\Mesa' shared service.
     *
     * @return \App\Entity\Mesa
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.a0WsX_G": it needs an instance of "App\\Entity\\Mesa" but this type has been excluded in "config/services.yaml".');
    }
}
