<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSrZjiuP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSrZjiuP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSrZjiuP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSrZjiuP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSrZjiuP\App_KernelDevDebugContainer([
    'container.build_hash' => 'SrZjiuP',
    'container.build_id' => '56efb73a',
    'container.build_time' => 1708895796,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSrZjiuP');
