<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX1M8XuH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX1M8XuH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerX1M8XuH.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerX1M8XuH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerX1M8XuH\App_KernelDevDebugContainer([
    'container.build_hash' => 'X1M8XuH',
    'container.build_id' => '19630e9a',
    'container.build_time' => 1708810313,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX1M8XuH');
