<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOILLBnu\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOILLBnu/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOILLBnu.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOILLBnu\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOILLBnu\App_KernelDevDebugContainer([
    'container.build_hash' => 'OILLBnu',
    'container.build_id' => '407ec5da',
    'container.build_time' => 1708797632,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOILLBnu');
